name: Deploy Pull Request Preview

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci

      - name: Build with dynamic base path
        run: |
          export BASE_PATH="/pr-preview/${{ github.event.pull_request.number }}/"
          npm run build
        env:
          BASE_PATH: "/pr-preview/${{ github.event.pull_request.number }}/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./dist

  deploy:
    if: github.event.action != 'closed'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./dist

      - name: Deploy to PR preview subpath
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
