# .github/workflows/preview.yml
name: Deploy PR Previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "preview-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and build
        uses: withastro/action@v4
        with:
          node-version: '22.x'
          # The output directory for your Astro build is typically 'dist'
          # This action will automatically use it.

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.5.0
        with:
          source-dir: './dist' # This should match your Astro build output directory
          preview-branch: 'gh-pages' # A dedicated branch for previews

  remove-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Remove PR Preview
        uses: rossjrw/pr-preview-action@v1.5.0
        with:
          action: 'remove'
          preview-branch: 'gh-pages' # Must match the preview-branch above
