# .github/workflows/preview.yml

name: Deploy Pull Request Preview

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]

jobs:
  # Build the Astro site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build with Astro
        run: npm run build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/

  # Cleanup job to remove the sticky comment when PR is closed
  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Remove Preview Link Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: astro-preview
          message: 'The preview for this PR has been deactivated.'
